name: "DAST"

on:
  push:
    branches:
      - main
      - 'release/*'
      - master
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          
      - name: Start Local Server
        run: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py runserver 0.0.0.0:8000 & sleep 10

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: "http://localhost:8000"

