name: "DAST"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Start Local Server
        run: |
            python -m venv venv
            source venv/bin/activate
            python manage.py runserver 0.0.0.0:8000 & sleep 15

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          token: ${{ secrets.GITHUB_TOKEN }}
          target: "http://localhost:8000"

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: dast-report
          path: report-report.html
        

