name: License 

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  license-check:
    name: License Compliance Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      - name: Run License Compliance Check
        uses: dhatim/pip-licenses-action@v1
        with:
          output_file: license-report.csv
          output_format: csv

      - name: Upload License Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: license-compliance-report
          path: license-report.csv
