name: License

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run License Compliance Check
        uses: docker://ghcr.io/fjogeleit/license-checker:latest
        with:
          args: >
            --json ./license-checker-report.json
            --path .
            --failOn "error"

      - name: Upload License Report
        uses: actions/upload-artifact@v3
        with:
          name: license-compliance-report
          path: license-checker-report.json
