name: License 

on:
  push:
    branches:
      - main
      - 'release/*'
      - master
  pull_request:

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: License compliance check
        uses: mikaelvesavuori/license-compliance-action@v1